create or replace PROCEDURE "AD_STP_UPD_VARIACAO_CAMBIAL" (
       P_CODUSU NUMBER,       
       P_IDSESSAO VARCHAR2,    
       P_QTDLINHAS NUMBER,     
       P_MENSAGEM OUT VARCHAR2 
) AS

       PARAM_DATAREF 			DATE;
       FIELD_NUFIN 				NUMBER;  
	   V_VLRVARCAMB 			FLOAT;
	   V_VLRVARCAMBLANC 		FLOAT;
	   V_COTACAO 				FLOAT;
	   V_VLRMODFUN 				FLOAT;
	   V_COUNT_VARCAMB 			INT;
       V_SEQUENCIA 				INT;
       P_TEM_REG_FUTURO         INT;
       P_TEM_REG_BAIXADO        INT;
	   V_DTMOV 					DATE;
       V_TIPO                   VARCHAR(10);

BEGIN  

 FOR I IN  1..P_QTDLINHAS 
 LOOP 

	FIELD_NUFIN := ACT_INT_FIELD(P_IDSESSAO, I,'NUFIN'); 
    PARAM_DATAREF := ACT_DTA_PARAM(P_IDSESSAO,'DTREF'); 

	/*
	VALIDAR QUE A DATA DE REFERENCIA DO PARAMETRO FOI INFORMADA
	*/
	IF PARAM_DATAREF IS NULL THEN 
	RAISE_APPLICATION_ERROR(-20101, 'Necessário preencher a data de referência');
	END IF;

DELETE 
FROM AD_VARCAMB 
WHERE NUFIN = FIELD_NUFIN
AND LAST_DAY(DTVAR) = LAST_DAY(PARAM_DATAREF);

FOR CUR IN (
/*
FINANCEIROS QUE IRÃO FAZER PARTE DO CÁLCULO DA VARIAÇÃO CAMBIAL
*/
SELECT NUFIN,VLRMOEDA,CODTIPOPERBAIXA,CODPROJ,DTREF,VLRDESDOB,TIPO,TIPON,VLRUS,AD_CALCVARCAMB
FROM (
/*
CONSULTA DE FINANCEIROS EM ABERTO
*/
SELECT FIN.NUFIN,NVL(FIN.VLRMOEDA,0) AS VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ,FIN.DTNEG  AS "DTREF" ,FIN.VLRDESDOB,
	   (CASE WHEN NVL(FIN.VLRMOEDA,0) = 0 THEN 0 ELSE (FIN.VLRDESDOB/FIN.VLRMOEDA) END) AS "VLRUS", 'ABERTO' AS "TIPO",
	   '1' AS TIPON,NVL(FIN.AD_CALCVARCAMB,'N') AS "AD_CALCVARCAMB"
FROM TGFFIN FIN
INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND TPO.DHALTER = FIN.DHTIPOPER
WHERE 1=1 
AND NAT.AD_CALCVARCAMB = 'S'    
AND FIN.VLRMOEDA > 0
AND FIN.RECDESP <> 0   
AND FIN.DTNEG <= PARAM_DATAREF 
AND CAB.CODTIPOPERBAIXA = 0

UNION ALL
/*
LEITURA BAIXADOS
*/
SELECT FIN.NUFIN,NVL(FIN.VLRMOEDA,0) as VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ,FIN.DHBAIXA as DTREF,FIN.VLRDESDOB,
	   (CASE WHEN NVL(FIN.VLRMOEDA,0) = 0 THEN 0 ELSE (FIN.VLRDESDOB/FIN.VLRMOEDA) END) AS "VLRUS", 'BAIXADO' AS "TIPO" ,
	   '3' AS "TIPON",NVL(FIN.AD_CALCVARCAMB,'N') AS "AD_CALCVARCAMB"
FROM TGFFIN FIN
INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND TPO.DHALTER = FIN.DHTIPOPER
WHERE 1=1  
AND NAT.AD_CALCVARCAMB = 'S'  
AND FIN.CODTIPOPERBAIXA > 0
AND FIN.VLRMOEDA > 0 
AND FIN.RECDESP <> 0  
AND (FIN.DHBAIXA >=  TO_CHAR(TRUNC(PARAM_DATAREF,'MM'),'DD-MM-YYYY') AND FIN.DHBAIXA <= PARAM_DATAREF)

UNION ALL
/*
LEITURA NACIONALIZADOS
*/
SELECT DISTINCT FIN.NUFIN,NVL(FIN.VLRMOEDA,0) as VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ, MAX(CAB.DTNEG) AS DTREF,FIN.VLRDESDOB,
				(CASE WHEN NVL(FIN.VLRMOEDA,0) = 0 THEN 0 ELSE FIN.VLRDESDOB/FIN.VLRMOEDA END) AS "VLRUS" ,'NACIONALIZADO' AS TIPO, 
				'2' AS TIPON,'N' AS "AD_CALCVARCAMB"
FROM TGFFIN FIN 
INNER JOIN TCSPRJ PRJ ON PRJ.CODPROJ = FIN.CODPROJ 
INNER JOIN TGFCAB CAB ON CAB.CODPROJ = FIN.CODPROJ   
INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND TPO.DHALTER = FIN.DHTIPOPER
WHERE 1=1 
AND FIN.VLRMOEDA > 0 
AND FIN.CODPROJ <> 0 
AND FIN.RECDESP <> 0
AND NAT.AD_CALCVARCAMB = 'S' 
AND CAB.CODTIPOPER = 26
AND TO_CHAR(FIN.DTNEG,'MM-YYYY') = TO_CHAR(CAB.DTNEG,'MM-YYYY')
GROUP BY FIN.NUFIN,FIN.VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ,FIN.VLRDESDOB 
) T 
WHERE 1=1  
AND TO_CHAR(DTREF,'MM-YYYY') = TO_CHAR(PARAM_DATAREF,'MM-YYYY')
AND NUFIN =  FIELD_NUFIN  
AND AD_CALCVARCAMB = 'N'
AND VLRMOEDA <> 0 
ORDER BY NUFIN,TIPON,DTREF
)

LOOP  
	/*
	VERIFICANDO SE EXISTE REGISTRO NA TABELA DE VARIAÇÃO DE CAMBIO
	*/
	SELECT NVL(MAX(SEQUENCIA),0) 
	INTO V_COUNT_VARCAMB 
	FROM AD_VARCAMB 
	WHERE NUFIN = FIELD_NUFIN
	AND DTVAR <= CUR.DTREF; 

	/*
    VALOR DA COTAÇÃO NA DATA INFORMADA NO PARAMETRO
    */  
    SELECT DTMOV,COTACAO 
    INTO V_DTMOV, V_COTACAO 
    FROM TSICOT 
    WHERE 1=1 
    AND CODMOEDA = 1   
    AND ROWNUM = 1
    AND  DTMOV  <=  CUR.DTREF 
    ORDER BY DTMOV DESC; 

	/*
	VALIDAÇAO DE REGISTRO FUTURO 	
	*/
	SELECT COUNT(*)
    INTO P_TEM_REG_FUTURO
    FROM AD_VARCAMB
	WHERE DTVAR > CUR.DTREF
    AND NUFIN = FIELD_NUFIN;

	/*
	SE NÃO POSSUI VALOR EM DOLAR BLOQUEIA A OPERAÇÃO
	*/
	IF CUR.VLRMOEDA = 0 THEN 

	RAISE_APPLICATION_ERROR(-20101,'Moeda não Informada para o Título Selecionado. Verifique ' + CUR.NUFIN );

	END IF;

	/*
	SE TEM REGISTRO FUTURO BLOQUEIA O CÁLCULO

	IF P_TEM_REG_FUTURO <> 0 THEN

	RAISE_APPLICATION_ERROR(-20101, 'Existem registros de Variação Cambial em data futura. Verifique');

	END IF;
    */
	/*
    IF PARA VERIFICAR SE EXISTE REGISTRO NA TABELA DE VARIAÇÃO, CASO EXISTA, SALVAR OS DADOS DO ULTIMO REGISTRO DA VARIACAO CAMBIAL
    */
    IF V_COUNT_VARCAMB > 0 THEN 
	SELECT NVL(VLRMODFUN,0) AS "VLRMODFUN",NVL(VLRVARCAMB,0) AS "VLRVARCAMB",NVL(VLRVARCAMBLANC,0) AS "VLRVARCAMBLANC"
	INTO V_VLRMODFUN,V_VLRVARCAMB,V_VLRVARCAMBLANC
	FROM AD_VARCAMB
	WHERE 1=1  
	AND NUFIN = FIELD_NUFIN 
	AND  DTVAR =  (SELECT MAX(VAR.DTVAR) 
					FROM AD_VARCAMB VAR
					WHERE VAR.NUFIN = FIELD_NUFIN
					AND VAR.DTVAR <= CUR.DTREF)
	ORDER BY DTVAR DESC; 
    END IF;


    /*VERIFICANDO SE O REGISTRO JA FOI BAIXADO*/
    SELECT COUNT(TIPO) INTO P_TEM_REG_BAIXADO 
    FROM AD_VARCAMB 
    WHERE NUFIN = FIELD_NUFIN AND TIPO = '3';

    /* 
    INSERT REGISTRO ABERTO
    */
    IF CUR.TIPON = '1' AND CUR.AD_CALCVARCAMB = 'N' THEN 

    INSERT INTO AD_VARCAMB (NUFIN,SEQUENCIA,DTVAR,DTINC,VLRMOEDA,VLRMOEDAVAR,VLRMODFUN,VLRMODFUNATUAL,VLRMODUS,VLRVARCAMB,VLRVARCAMBLANC,TIPO,VARCALC)
	VALUES(FIELD_NUFIN,(SELECT NVL(MAX(SEQUENCIA)+1,1) FROM AD_VARCAMB WHERE NUFIN = FIELD_NUFIN),CUR.DTREF,SYSDATE,CUR.VLRMOEDA,V_COTACAO,CUR.VLRDESDOB,CUR.VLRUS*V_COTACAO,CUR.VLRDESDOB/CUR.VLRMOEDA,(CUR.VLRUS*V_COTACAO)-CUR.VLRDESDOB,(((CUR.VLRUS*V_COTACAO)-CUR.VLRDESDOB) - NVL(V_VLRVARCAMBLANC,0)),CUR.TIPON,'N');

    END IF;

    /*
    INSERT NACIONALIZAÇÃO
    */
    IF CUR.TIPON = '2' AND CUR.AD_CALCVARCAMB = 'N' THEN
	INSERT INTO AD_VARCAMB (NUFIN,SEQUENCIA,DTVAR,DTINC,VLRMOEDA,VLRMOEDAVAR,VLRMODFUN,VLRMODFUNATUAL,VLRMODUS,VLRVARCAMB,VLRVARCAMBLANC,TIPO,VARCALC)
	VALUES(FIELD_NUFIN,(SELECT NVL(MAX(SEQUENCIA)+1,1) FROM AD_VARCAMB WHERE NUFIN = FIELD_NUFIN),CUR.DTREF,SYSDATE,CUR.VLRMOEDA,V_COTACAO,CUR.VLRDESDOB,CUR.VLRUS*V_COTACAO,CUR.VLRDESDOB/CUR.VLRMOEDA,(CUR.VLRUS*V_COTACAO)-CUR.VLRDESDOB,(((CUR.VLRUS*V_COTACAO)-CUR.VLRDESDOB) - NVL(V_VLRVARCAMBLANC,0)),CUR.TIPON,'S');

	 	END IF;

	/*
	INSERT REGISTRO BAIXADO
	*/	  
    IF CUR.TIPON = '3' AND CUR.AD_CALCVARCAMB = 'N' THEN
	INSERT INTO AD_VARCAMB (NUFIN,SEQUENCIA,DTVAR,DTINC,VLRMOEDA,VLRMOEDAVAR,VLRMODFUN,VLRMODFUNATUAL,VLRMODUS,VLRVARCAMB,VLRVARCAMBLANC,TIPO,VARCALC)
	VALUES(FIELD_NUFIN,(SELECT NVL(MAX(SEQUENCIA)+1,1) FROM AD_VARCAMB WHERE NUFIN = FIELD_NUFIN),CUR.DTREF,SYSDATE,CUR.VLRMOEDA,V_COTACAO,CUR.VLRDESDOB,CUR.VLRUS*V_COTACAO,CUR.VLRDESDOB/CUR.VLRMOEDA,(CUR.VLRUS*V_COTACAO)-CUR.VLRDESDOB,(((CUR.VLRUS*V_COTACAO)-CUR.VLRDESDOB) - NVL(V_VLRVARCAMBLANC,0)),CUR.TIPON,'S');

    UPDATE AD_VARCAMB SET VARCALC = 'S'  WHERE NUFIN = FIELD_NUFIN AND TIPO = '1';
    END IF;


  END LOOP;
 END LOOP;
 P_MENSAGEM := 'Calculo da variação cambial realizado com sucesso!';
END;