SELECT NUFIN,LISTAGG(TIPO,',') WITHIN GROUP(ORDER BY TIPO) AS TIPO,NOMEPARC,CODNAT,DESCRNAT,LISTAGG(TOP,',') AS "TOP",TOPTITULO,DESCROPER,DT_NEGOCIACAO,DTREF
FROM (  
SELECT DISTINCT TIPO,NUFIN,NOMEPARC,CODNAT,TOP,DESCRNAT,TOPTITULO,DESCROPER, DT_NEGOCIACAO,DTREF,AD_CALCVARCAMB 
FROM (

/*
DADOS DO FINANCEIRO EM ABERTO
*/

SELECT FIN.NUFIN,FIN.VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ,FIN.DTNEG AS DTREF,FIN.VLRDESDOB,ROUND(FIN.VLRDESDOB/FIN.VLRMOEDA,4) as VLRUS, 'ABERTO' as TIPO,
PAR.NOMEPARC,NAT.CODNAT,FIN.CODTIPOPER AS TOP,NAT.DESCRNAT,FIN.CODTIPOPER AS "TOPTITULO",TPO.DESCROPER,FIN.DTNEG as "DT_NEGOCIACAO",NVL(FIN.AD_CALCVARCAMB,'N') AS "AD_CALCVARCAMB"
FROM TGFFIN FIN
INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND TPO.DHALTER = FIN.DHTIPOPER
INNER JOIN TGFPAR PAR ON PAR.CODPARC  = FIN.CODPARC
WHERE 1=1 
AND NAT.AD_CALCVARCAMB = 'S'    
AND FIN.VLRMOEDA > 0
AND FIN.RECDESP <> 0  
AND FIN.DTNEG <= :DTREF

UNION ALL

/*
DADOS DO FINANCEIRO BAIXADO
*/

SELECT FIN.NUFIN,FIN.VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ,FIN.DHBAIXA as DTREF,FIN.VLRDESDOB,ROUND(FIN.VLRDESDOB/FIN.VLRMOEDA,4) as VLRUS, 'BAIXADO' as TIPO,
PAR.NOMEPARC,NAT.CODNAT,FIN.CODTIPOPERBAIXA AS "TOP",NAT.DESCRNAT,FIN.CODTIPOPER AS "TOPTITULO",TPO.DESCROPER,FIN.DTNEG as "DT_NEGOCIACAO",NVL(FIN.AD_CALCVARCAMB,'N') AS "AD_CALCVARCAMB"
FROM TGFFIN FIN
INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND TPO.DHALTER = FIN.DHTIPOPER
INNER JOIN TGFPAR PAR ON PAR.CODPARC  = FIN.CODPARC
WHERE 1=1  
AND NAT.AD_CALCVARCAMB = 'S'  
AND FIN.CODTIPOPERBAIXA > 0
AND FIN.VLRMOEDA > 0    
AND FIN.RECDESP <> 0 
AND (FIN.DHBAIXA >=  TO_CHAR(TRUNC(:DTREF,'MM'),'DD-MM-YYYY') AND FIN.DHBAIXA <= :DTREF)

UNION ALL

/*
DADOS DO CABEÇALHO COM NACIONALIZAÇÃO
*/
SELECT * FROM (
SELECT DISTINCT FIN.NUFIN,FIN.VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ, MAX(CAB.DTNEG) AS DTREF,FIN.VLRDESDOB ,ROUND(FIN.VLRDESDOB/FIN.VLRMOEDA,4) as VLRUS, 'NACIONALIZADO' AS "TIPO",
PAR.NOMEPARC,NAT.CODNAT,CAB.CODTIPOPER AS "TOP",NAT.DESCRNAT,FIN.CODTIPOPER AS "TOPTITULO",TPO.DESCROPER,CAB.DTNEG as "DT_NEGOCIACAO",'N' AS "AD_CALCVARCAMB"
FROM TGFFIN FIN 
INNER JOIN TCSPRJ PRJ ON PRJ.CODPROJ = FIN.CODPROJ 
INNER JOIN TGFCAB CAB ON CAB.CODPROJ = FIN.CODPROJ   
INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND TPO.DHALTER = FIN.DHTIPOPER
INNER JOIN TGFPAR PAR ON PAR.CODPARC  = FIN.CODPARC
WHERE 1=1 
AND FIN.VLRMOEDA > 0
AND TO_CHAR(FIN.DTNEG,'MM-YYYY') = TO_CHAR(CAB.DTNEG,'MM-YYYY')

AND FIN.CODPROJ <> 0 
AND FIN.RECDESP <> 0
AND NAT.AD_CALCVARCAMB = 'S'
AND CAB.CODTIPOPER = 26
GROUP BY FIN.NUFIN,FIN.VLRMOEDA,FIN.CODTIPOPERBAIXA,FIN.CODPROJ,FIN.VLRDESDOB,PAR.NOMEPARC,NAT.CODNAT,CAB.CODTIPOPER,
NAT.DESCRNAT,FIN.CODTIPOPER,TPO.DESCROPER,CAB.DTNEG) C 
WHERE 1=1
AND (DT_NEGOCIACAO >=  TO_CHAR(TRUNC(:DTREF,'MM'),'DD-MM-YYYY') AND DT_NEGOCIACAO <= :DTREF)
 

) T /*SEGUNDO SELECT (SELECT COM DISTINCT) */
WHERE 1=1  
AND NUFIN = NVL(:NUFIN,NUFIN)  
AND AD_CALCVARCAMB = 'N'
) /*PRIMEIRO SELECT*/
WHERE 1=1
AND TIPO IN :TIPO
GROUP BY NUFIN,NOMEPARC,CODNAT,DESCRNAT,TOPTITULO,DESCROPER,DT_NEGOCIACAO,DTREF
ORDER BY 1,2