create or replace NONEDITIONABLE TRIGGER AD_TRG_UPD_TGFCAB_LOTE 
BEFORE UPDATE ON TGFCAB 
FOR EACH ROW

DECLARE 

PRAGMA AUTONOMOUS_TRANSACTION;
V_COUNT            INT; 
V_NUNOTA           INT;

BEGIN
/*
Glaycon Henrique - 27/02/2023
Processo: Automatizar numeração do lote de acordo com o numero da nota fiscal
Este objeto trabalha em conjunto com o objeto na ITE, cujo nome: XXXXt
*/     
    /*
    VERIFICANDO SE EXISTE PRODUTO MARCADO PARA TER CONTROLE POR LOTE QUANDO O UPDATE É FEITO NO NUMNOTA
    */
    IF (UPDATING ('NUMNOTA') AND :NEW.NUMNOTA > 0 AND :NEW.TIPMOV = 'C') AND :NEW.CODPARC = 61 THEN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM TGFITE ITE
    INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD AND PRO.TIPCONTEST = 'L'
    WHERE  1=1
    AND ITE.NUNOTA = :NEW.NUNOTA;
    --AND ITE.CONTROLE = ' '; -- VERIFICAR NECESSIDADE COM O JOVEM (POIS SE FOR IMPORTADO COM LOTE, ALTERAR DO MESMO JEITO OU NÃO
    END IF;

    IF V_COUNT > 0 AND :NEW.CODPARC = 61 THEN
    UPDATE TGFITE ITE SET ITE.CONTROLE = :NEW.NUMNOTA
    WHERE 1=1
    AND EXISTS (SELECT 1 FROM TGFPRO PRO WHERE PRO.CODPROD=ITE.CODPROD AND PRO.TIPCONTEST = 'L' AND ITE.NUNOTA = :NEW.NUNOTA)
    AND ITE.NUNOTA = :NEW.NUNOTA;
    COMMIT;
    END IF;

END;